server:
  port: 9002
#服务名称
spring:
  application:
    name: nacos-payment-provider
  #    注入端口
  cloud:
    nacos:
      server-addr: http://localhost:8848

#    #监控的目录
management:
  endpoints:
    web:
      exposure:
        include: "*"