server:
  port: 2002
spring:
  application:
    name: seata-storage-service
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.237.129:8088
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:8080
    alibaba:
      seata:
        #对应seata.conf 里面的seata-server
        tx-service-group: fsp_tx_group
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://192.168.237.129:3306/seata_storage?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&allowMultiQueries=true&allowPublicKeyRetrieval=true

management:
  endpoints:
    web:
      exposure:
        include: "*"
#使用feign调用
feign:
  sentinel:
    enabled: true

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml

swagger:
  groupName: storage
  basePackage: com.alibaba.storage.controller
  title: 库存模块
seata:
  client:
    support:
      spring:
        datasource-autoproxy: false