server:
  port: 8401
spring:
  application:
    name: cloudalibaba-sentinel-service
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.237.129:8088

    sentinel:
      transport:
#        配置sentinel dashboard地址
#        dashboard: localhost:8080
#        默认8719端口，加入被占用会自动从8719开始一次＋1扫描，知道找到未被占用的端口
        port: 8719
        dashboard: localhost:8080
      datasource:
        ds1:
          nacos:
            server-addr: 192.168.237.129:8088
            dataId: cloudalibaba-sentinel-service
            groupId: DEFAULT_GROUP
            data-type: json
            rule-type: flow
    #        监控
management:
  endpoints:
    web:
      exposure:
        include: "*"
#使用feign调用
feign:
  sentinel:
    enabled: true