server:
  port: 9001
#服务名称
spring:
  application:
    name: nacos-payment-provider
#    注入端口
  cloud:
    nacos:
#      server-addr: http://localhost:8848
      server-addr: http://192.168.237.129:8088

##监控的目录
#management:
#  endpoints:
#    web:
#      exposure:
#        include: *
